name: elas_mcf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fundo.png
    - assets/leis_publicas.png
    - assets/instituicoes_apoio.png
    - assets/numeros_emergencia.png
    - assets/sos.png
    - assets/seta.png
